# Generated by Django 2.2.10 on 2020-02-14 19:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
