# Generated by Django 2.2.10 on 2020-02-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20200214_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='name',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
